version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: board_user
      POSTGRES_PASSWORD: board_pass
      POSTGRES_DB: board_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - triple-s
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: board_user
      DB_PASSWORD: board_pass
      DB_NAME: board_db  

      TRIPLE_S_HOST: triple-s
      TRIPLE_S_PORT: 9000
      TRIPLE_S_ACCESS_KEY: "your_access_key"
      TRIPLE_S_SECRET_KEY: "your_access_key"    
  
  triple-s:
    build:
      context: ./triple-s  # Папка с проектом triple-s
    ports:
      - "9000:9000"
    environment:
      TRIPLE_S_ACCESS_KEY: "your_access_key" # Установи ключ доступа
      TRIPLE_S_SECRET_KEY: "your_secret_key" # Установи секретный ключ
    volumes:
      - triple_s_data:/data

volumes:
  db_data:
  triple_s_data:
